FROM node:22.22.2-alpine3.22

RUN apk upgrade --no-cache

WORKDIR /workspace/client-policy-intel

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]