import { useState } from "react";
import { api, type Deliverable } from "../api";
import { useAsync } from "../hooks";

const TYPE_COLORS: Record<string, string> = {
  brief: "#1565c0",
  memo: "#6a1b9a",
  summary: "#2e7d32",
  report: "#e65100",
  talking_points: "#00838f",
};

function typeColor(type: string) {
  return TYPE_COLORS[type.toLowerCase()] ?? "#546e7a";
}

export function DeliverablesPage() {
  const { data: deliverables, loading, error } = useAsync(() => api.getDeliverables());
  const [selected, setSelected] = useState<Deliverable | null>(null);
  const [typeFilter, setTypeFilter] = useState("all");

  if (loading) return <p>Loading deliverables...</p>;
  if (error) return <p style={{ color: "red" }}>{error}</p>;

  const allTypes = Array.from(new Set((deliverables ?? []).map((d) => d.type.toLowerCase()))).sort();

  const filtered = (deliverables ?? []).filter(
    (d) => typeFilter === "all" || d.type.toLowerCase() === typeFilter,
  );

  return (
    <div style={{ display: "grid", gridTemplateColumns: selected ? "1fr 420px" : "1fr", gap: 24 }}>
      {/* List panel */}
      <div>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
          <h1 style={{ fontSize: 22, margin: 0 }}>Briefs &amp; Deliverables</h1>
          <span style={{ fontSize: 13, color: "#888" }}>{(deliverables ?? []).length} total</span>
        </div>

        <div style={{ display: "flex", gap: 6, marginBottom: 16, flexWrap: "wrap" }}>
          {(["all", ...allTypes] as const).map((t) => (
            <button
              key={t}
              onClick={() => setTypeFilter(t)}
              style={{
                padding: "5px 12px",
                borderRadius: 14,
                border: "none",
                cursor: "pointer",
                fontSize: 12,
                fontWeight: typeFilter === t ? 600 : 400,
                background: typeFilter === t ? (t === "all" ? "#3498db" : typeColor(t)) : "#e0e0e0",
                color: typeFilter === t ? "#fff" : "#555",
              }}
            >
              {t.replace(/_/g, " ")}
              {t !== "all" && (
                <span style={{ marginLeft: 4, opacity: 0.75 }}>
                  ({(deliverables ?? []).filter((d) => d.type.toLowerCase() === t).length})
                </span>
              )}
            </button>
          ))}
        </div>

        {filtered.length === 0 && (
          <p style={{ color: "#888", fontSize: 13 }}>No deliverables found.</p>
        )}

        <div style={{ display: "grid", gap: 10 }}>
          {filtered.map((d) => (
            <DeliverableRow
              key={d.id}
              deliverable={d}
              selected={selected?.id === d.id}
              onClick={() => setSelected(selected?.id === d.id ? null : d)}
            />
          ))}
        </div>
      </div>

      {/* Detail panel */}
      {selected && (
        <div style={{
          background: "#fff",
          borderRadius: 8,
          padding: "20px 24px",
          boxShadow: "0 2px 8px rgba(0,0,0,0.1)",
          alignSelf: "start",
          position: "sticky",
          top: 0,
          maxHeight: "90vh",
          overflow: "auto",
        }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16 }}>
            <h2 style={{ fontSize: 16, margin: 0, flex: 1, marginRight: 12 }}>{selected.title}</h2>
            <button
              onClick={() => setSelected(null)}
              style={{ background: "none", border: "none", cursor: "pointer", fontSize: 18, color: "#888", padding: 0 }}
            >
              ×
            </button>
          </div>

          <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
            <span style={{
              padding: "2px 10px",
              borderRadius: 10,
              fontSize: 11,
              fontWeight: 600,
              background: typeColor(selected.type) + "18",
              color: typeColor(selected.type),
            }}>
              {selected.type.replace(/_/g, " ")}
            </span>
            {selected.matterId && (
              <span style={{ fontSize: 11, color: "#888" }}>Matter #{selected.matterId}</span>
            )}
          </div>

          <div style={{ fontSize: 11, color: "#aaa", marginBottom: 16 }}>
            Generated by {selected.generatedBy} · {new Date(selected.createdAt).toLocaleString()}
          </div>

          {selected.bodyMarkdown ? (
            <div style={{ fontSize: 13, color: "#333", lineHeight: 1.7, whiteSpace: "pre-wrap", wordBreak: "break-word" }}>
              {selected.bodyMarkdown}
            </div>
          ) : (
            <p style={{ color: "#aaa", fontSize: 13 }}>No content available.</p>
          )}
        </div>
      )}
    </div>
  );
}

function DeliverableRow({
  deliverable: d,
  selected,
  onClick,
}: {
  deliverable: Deliverable;
  selected: boolean;
  onClick: () => void;
}) {
  const color = typeColor(d.type);
  const preview = d.bodyMarkdown?.slice(0, 160).replace(/\n/g, " ");

  return (
    <div
      onClick={onClick}
      style={{
        background: selected ? "#f0f7ff" : "#fff",
        borderRadius: 8,
        padding: "12px 16px",
        boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
        borderLeft: `4px solid ${selected ? "#3498db" : color}`,
        cursor: "pointer",
        transition: "background 0.1s",
      }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 13, fontWeight: 600 }}>{d.title}</div>
          {preview && (
            <div style={{ fontSize: 11, color: "#777", marginTop: 4 }}>{preview}…</div>
          )}
        </div>
        <div style={{ textAlign: "right", flexShrink: 0, marginLeft: 12 }}>
          <span style={{
            padding: "2px 8px",
            borderRadius: 10,
            fontSize: 11,
            fontWeight: 600,
            background: color + "18",
            color,
          }}>
            {d.type.replace(/_/g, " ")}
          </span>
          <div style={{ fontSize: 10, color: "#aaa", marginTop: 4 }}>
            {new Date(d.createdAt).toLocaleDateString()}
          </div>
        </div>
      </div>
    </div>
  );
}
