name: Workflow Lint

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - ".github/workflows/**"
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint workflows
        uses: docker://rhysd/actionlint:1.7.8
        with:
          args: -color